export enum ElementEnum {
    LOGIN_BUTTON_ACTION = "login-button-action",
    LOGIN_BUTTON_BLOCK = "login-button-block",
    JIRA_CONNECT_ACTION = "jira-connect-action",
    JIRA_CONNECT_BLOCK = "jira-connect-block",
    JIRA_PROJECT_SELECT_ACTION = "jira-project-select-action",
    JIRA_PROJECT_SELECT_BLOCK = "jira-project-select-block",
    JIRA_CREATE_ISSUE_TYPE_ACTION = "jira-create-issue-type-action",
    JIRA_CREATE_ISSUE_TYPE_BLOCK = "jira-create-issue-type-block",
    JIRA_CREATE_ISSUE_SUMMARY_ACTION = "jira-create-issue-summary-action",
    JIRA_CREATE_ISSUE_SUMMARY_BLOCK = "jira-create-issue-summary-block",
    JIRA_CREATE_ISSUE_DESCRIPTION_ACTION = "jira-create-issue-description-action",
    JIRA_CREATE_ISSUE_DESCRIPTION_BLOCK = "jira-create-issue-description-block",
    JIRA_CREATE_ISSUE_PRIORITY_ACTION = "jira-create-issue-priority-action",
    JIRA_CREATE_ISSUE_PRIORITY_BLOCK = "jira-create-issue-priority-block",
    JIRA_CREATE_ISSUE_ASSIGNEE_ACTION = "jira-create-issue-assignee-action",
    JIRA_CREATE_ISSUE_ASSIGNEE_BLOCK = "jira-create-issue-assignee-block",
    JIRA_CREATE_ISSUE_DEADLINE_ACTION = "jira-create-issue-deadline-action",
    JIRA_CREATE_ISSUE_DEADLINE_BLOCK = "jira-create-issue-deadline-block",
    JIRA_CREATE_ISSUE_SUBMIT_ACTION = "jira-create-issue-submit-action",
    JIRA_CREATE_ISSUE_SUBMIT_BLOCK = "jira-create-issue-submit-block",
}